version: 2


sources:
  - name: staging
    description: "Raw data from NYC taxi rides"
    database: ZOOMCAMP
    schema: TRIPS

    tables:
      - name: GREEN_TRIPDATA
      - name: YELLOW_TRIPDATA